// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWCSOQCupHUigKjmQ7igIg8awjVQDJPnI',
    appId: '1:863205658684:web:1d20b624b1f6634d973339',
    messagingSenderId: '863205658684',
    projectId: 'dat-san-the-thao',
    authDomain: 'dat-san-the-thao.firebaseapp.com',
    storageBucket: 'dat-san-the-thao.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPp7uLZdUi_5-Tb1xM_Tszreuv1-01XpQ',
    appId: '1:863205658684:android:0bf075dbc820c80a973339',
    messagingSenderId: '863205658684',
    projectId: 'dat-san-the-thao',
    storageBucket: 'dat-san-the-thao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGSLEbTkLRCxJFWzxq1WV4OWgSuQECoI0',
    appId: '1:863205658684:ios:824e226af642af00973339',
    messagingSenderId: '863205658684',
    projectId: 'dat-san-the-thao',
    storageBucket: 'dat-san-the-thao.firebasestorage.app',
    iosBundleId: 'com.example.flutterDstt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGSLEbTkLRCxJFWzxq1WV4OWgSuQECoI0',
    appId: '1:863205658684:ios:824e226af642af00973339',
    messagingSenderId: '863205658684',
    projectId: 'dat-san-the-thao',
    storageBucket: 'dat-san-the-thao.firebasestorage.app',
    iosBundleId: 'com.example.flutterDstt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWCSOQCupHUigKjmQ7igIg8awjVQDJPnI',
    appId: '1:863205658684:web:f2c9a70a6b41abc5973339',
    messagingSenderId: '863205658684',
    projectId: 'dat-san-the-thao',
    authDomain: 'dat-san-the-thao.firebaseapp.com',
    storageBucket: 'dat-san-the-thao.firebasestorage.app',
  );
}
